image: ubuntu2004

environment:
  matrix:
  - TOXENV: py36
    PYTHON: "3.6"
  - TOXENV: py37
    PYTHON: "3.7"
  - TOXENV: py38
    PYTHON: "3.8"
  - TOXENV: py39
    PYTHON: "3.9"

stack: python $PYTHON

install:
- pip install tox
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0x51716619e084dab9
- sudo bash -c "echo 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/' >> /etc/apt/sources.list"
- sudo apt-get update
- sudo apt-get install -y r-base sqlcipher libsqlcipher-dev
- sudo R CMD javareconf
- cd /home/appveyor/projects
- sudo echo "install.packages('openVA', repos='https://cloud.r-project.org/'); q('no')" > Rpackages.R
- sudo Rscript Rpackages.R
- cd /home/appveyor/projects/openva-pipeline/
- pip install -r requirements.txt
- cd /home/appveyor/projects/openva-pipeline/tests
- chmod +x setup_test_databases.sh
- ./setup_test_databases.sh
- cd /home/appveyor/projects/openva-pipeline/

test_script:
- tox

build: off
